//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddFacility()
        {
            this.CancelInfoes = new HashSet<CancelInfo>();
        }
    
        public int FacilityCode { get; set; }
        public string FacilityName { get; set; }
        public string Venue { get; set; }
        public Nullable<int> MaxCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelInfo> CancelInfoes { get; set; }
    }
}
