//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingInfo
    {
        public int BookingTransID { get; set; }
        public int MemberID { get; set; }
        public int FacilityCode { get; set; }
        public int SlotID { get; set; }
        public System.DateTime Booking_Date_and_Time { get; set; }
    }
}
