//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityDetail
    {
        public int FacilityCode { get; set; }
        public string FacilityName { get; set; }
        public int Total { get; set; }
        public int BadConditionQuantity { get; set; }
        public Nullable<int> Available { get; set; }
    }
}
