//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberInformation()
        {
            this.CancelInfoes = new HashSet<CancelInfo>();
        }
    
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string MemberAdress { get; set; }
        public string PhoneNumber { get; set; }
        public string eMailID { get; set; }
        public string MemberCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelInfo> CancelInfoes { get; set; }
        public virtual MemberCategory MemberCategory1 { get; set; }
    }
}
